version: '3.8'

services:
  runtime:
    build: .
    volumes:
      - .:/usr/local/${PROJECT_NAME}
    working_dir: /usr/local/${PROJECT_NAME}
    environment:
      - APP_DIR=/usr/local/${PROJECT_NAME}
    command: bash /usr/local/extra/startup.sh
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${PROJECT_NAME}0
